def step (chave):

    step = {
        '0': 'kinicio|CODIGO|kim',
        '1': 'î',
        '2': '<INSTRUCAO>|;|<CODIGO>',
        '3': 'î',
        '4': '<ESCREVA>',
        '5': '<LEIA>',
        '6': '<CONDICIONAL>',
        '7': '<REPETICAO>',
        '8': '<VARIAVEIS>',
        '9': '<ATRIBUICAO>',
        '10': 'eskreva|(|<EXPRESSOES>|)',
        '11': 'leiak|(| kid|)',
        '12': '<SE>|<SENAO>',
        '13': 'sek|(|<LOGICA>|)|{|<CODIGO>',
        '14': 'senaok|<CODIGO>|}',
        '15': 'î',
        '16': '<ENQUANTO>|fimenkuanto',
        '17': 'enkuanto|(|<LOGICA>|)|{| <CODIGO>',
        '18': 'kid|=|<EXPRESSAO>',
        '19': 'kint|kid',
        '20': 'kid|<OPERADORES>',
        '21': 'numeko|<OPERADORES>',
        '22': '+|<EXPRESSAO>',
        '23': '-|<EXPRESSAO>',
        '24': '(|<EXPRESSAO>|)|<OPERADORES>',
        '25': '+|<EXPRESSAO>',
        '26': '-|<EXPRESSAO>',
        '27': '*|<EXPRESSAO>',
        '28': '/|<EXPRESSAO>',
        '29': 'î',
        '30': 'kid',
        '31': 'numeko',
        '32': '<KID_OU_NUMEKO>|<OPERADOR_LOGICO>|<KID_OU_NUMEKO>',
        '33': 'string',
        '34': '<STRING>',
        '35': '<EXPRESSAO>',
        '36': '==',
        '37': '<'
    }
    return step[chave]
